apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-processor
  namespace: ecfr-analyzer
  labels:
    app: job-processor
spec:
  replicas: 8  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: job-processor
  template:
    metadata:
      labels:
        app: job-processor
    spec:
      serviceAccountName: job-processor-sa  
      containers:
      - name: job-processor
        image: a # Replace with your ECR registry
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_host

        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_port

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_password
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: job-processor-config
              key: aws_region
        envFrom:
        - configMapRef:
            name: job-processor-config
        - secretRef:
            name: db-credentials
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 30
